import type { ItabDataKind } from "@/features/itab-widgets/itabWidgetRegistry";

export interface ItabFixture {
  kind: ItabDataKind;
  title: string;
  accent: string;
  hero: string;
  subline: string;
  meta: string;
  progress?: number;
  lines: string[];
  chips: string[];
  panelTitle?: string;
  panelDescription?: string;
}

const fixture = (
  kind: ItabDataKind,
  title: string,
  accent: string,
  hero: string,
  subline: string,
  meta: string,
  lines: string[],
  chips: string[],
  progress = 0.62,
): ItabFixture => ({
  kind,
  title,
  accent,
  hero,
  subline,
  meta,
  lines,
  chips,
  progress,
  panelTitle: `${title} 工具`,
  panelDescription:
    "Fixture-first StartDeck 本地数据，不使用 iTab 私有接口或账号数据。",
});

export const ITAB_WIDGET_FIXTURES: Record<string, ItabFixture> = {
  weather: fixture(
    "weather",
    "天气",
    "#4f8df7",
    "龙华 25°",
    "小雨 · AQI 优/35",
    "最高30° 最低24°",
    ["体感 27°", "湿度 82%", "东北风 2级", "30 分钟前"],
    ["预报", "空气", "刷新"],
    0.35,
  ),
  calendar: fixture(
    "calendar",
    "日历",
    "#ff6b6b",
    "20",
    "2026年5月 · 周三",
    "第140天 · 第21周",
    ["四月初四", "小满", "本周还剩 4 天", "今日无日程"],
    ["月", "周", "今"],
    0.57,
  ),
  hotsearch: fixture(
    "hotsearch",
    "热搜榜",
    "#ff5a3d",
    "热搜",
    "百度 · 微博 · 抖音",
    "10 分钟前",
    [
      "普京结束访华乘专机离京",
      "520当天国家发改委干了两件大事",
      "关键之年的关键会晤",
      "暴雨大暴雨持续",
    ],
    ["百度", "微博", "抖音"],
    0.76,
  ),
  countdown: fixture(
    "countdown",
    "倒数日",
    "#7c5cff",
    "10458天",
    "你在世界已经",
    "1997-10-01 起",
    ["距离生日 134 天", "纪念日模板", "每日自动重算"],
    ["编辑", "模板", "提醒"],
    0.68,
  ),
  memo: fixture(
    "memo",
    "备忘录",
    "#f4b400",
    "iTab 操作小技巧",
    "点击打开编辑",
    "本地保存",
    ["组件可拖拽调整大小", "右键可打开设置", "支持快捷记录"],
    ["编辑", "同步", "清空"],
    0.48,
  ),
  movieCalendar: fixture(
    "movieCalendar",
    "电影日历",
    "#4c4c3f",
    "20 五月",
    "豆瓣 7.2",
    "世上很多事情本无对错",
    [
      "影",
      "剧情/动作/武侠2018中国大陆 中国香港",
      "导演：张艺谋",
      "沛国都督子虞，从小被秘密囚禁，替身境州走入权力漩涡。",
    ],
    ["查看电影源→"],
    0.72,
  ),
  offwork: fixture(
    "offwork",
    "下班倒计时",
    "#0ea5e9",
    "休息时间",
    "发薪 21 天",
    "周五还有 2 天",
    ["儿童节 12 天", "今日工作 67%", "18:30 下班"],
    ["排班", "薪资", "假期"],
    0.67,
  ),
  nextHoliday: fixture(
    "nextHoliday",
    "下一个假期",
    "#22c55e",
    "端午节",
    "6.19 - 6.21",
    "还有 30 天",
    ["中秋节 9.25", "国庆节 10.01", "调休 1 天"],
    ["假期", "日历", "地区"],
    0.3,
  ),
  dailyQuote: fixture(
    "dailyQuote",
    "每日一言",
    "#8b5cf6",
    "自由",
    "有一样东西你是不能从人的手中夺去的",
    "维克多·弗兰克尔",
    [
      "那就是最宝贵的自由",
      "选择自己的态度",
      "选择自己的行为方式",
    ],
    ["换一句", "复制", "收藏"],
    0.56,
  ),
  poem: fixture(
    "poem",
    "今日诗词",
    "#16a34a",
    "垂杨紫陌洛城东",
    "总是当时携手处",
    "欧阳修 · 浪淘沙",
    ["游遍芳丛", "全文展开", "每日精选"],
    ["全文", "注释", "收藏"],
    0.6,
  ),
  woodenFish: fixture(
    "woodenFish",
    "电子木鱼",
    "#a16207",
    "已敲 2 次",
    "木鱼一敲，烦恼丢掉",
    "本地计数",
    ["今日目标 108", "连续 1 天", "点击敲一下"],
    ["敲", "重置", "音效"],
    0.02,
  ),
  clock: fixture(
    "clock",
    "时钟",
    "#06b6d4",
    "23:40",
    "05-20 周三",
    "Asia/Shanghai",
    ["秒针运行中", "24 小时制", "本地时间"],
    ["样式", "时区", "秒"],
    0.98,
  ),
  speedTest: fixture(
    "speedTest",
    "网速测试",
    "#0891b2",
    "待测试",
    "下载 -- Mbps",
    "手动运行",
    ["上传 -- Mbps", "延迟 -- ms", "历史 3 次"],
    ["开始", "历史", "设置"],
    0.15,
  ),
  dailyEnglish: fixture(
    "dailyEnglish",
    "今日英语",
    "#2563eb",
    "Light stretches longer",
    "光把疼痛拉得更长",
    "跟读 0/3",
    ["pain /peɪn/", "播放音频", "今日打卡"],
    ["播放", "跟读", "收藏"],
    0.33,
  ),
  foodPicker: fixture(
    "foodPicker",
    "今天吃什么",
    "#f97316",
    "开始",
    "今天吃什么",
    "8 个候选",
    ["牛肉面", "寿司", "麻辣烫", "沙拉"],
    ["开始", "菜单", "重置"],
    0.44,
  ),
  wallpaper: fixture(
    "wallpaper",
    "壁纸",
    "#14b8a6",
    "熊蜂在授粉",
    "StartDeck 壁纸库",
    "本地/公共来源",
    ["自然", "收藏 12", "适配桌面"],
    ["应用", "收藏", "分类"],
    0.8,
  ),
  todo: fixture(
    "todo",
    "待办事项",
    "#10b981",
    "2 项",
    "啊哒哒 · wqewqeq",
    "今日待办",
    ["评审实现", "补充测试", "已完成 1 项"],
    ["添加", "完成", "列表"],
    0.4,
  ),
  stock: fixture(
    "stock",
    "股市",
    "#ef4444",
    "九安医疗",
    "002432 · 70.68",
    "+4.4%",
    ["宁德时代 300750", "上证指数", "延迟行情"],
    ["自选", "刷新", "详情"],
    0.7,
  ),
  game2048: fixture(
    "game2048",
    "2048",
    "#f59e0b",
    "2048",
    "得分 2048",
    "最好 4096",
    ["2 4 8 16", "32 64 128", "本地游戏"],
    ["新局", "撤销", "继续"],
    0.64,
  ),
  qwertyLearner: fixture(
    "qwertyLearner",
    "Qwerty Learner",
    "#6366f1",
    "Qwerty",
    "当前单词 abandon",
    "课程 CET-4",
    ["进度 12/40", "正确率 93%", "外部打开"],
    ["练习", "课程", "链接"],
    0.3,
  ),
  exchangeRate: fixture(
    "exchangeRate",
    "汇率",
    "#0284c7",
    "100 CNY",
    "USD 14.66",
    "5-20 更新",
    ["HKD 114.7", "JPY 2168", "EUR 12.8"],
    ["基准", "刷新", "换算"],
    0.5,
  ),
  gradient: fixture(
    "gradient",
    "渐变色",
    "#ec4899",
    "linear",
    "#7C3AED → #06B6D4",
    "45deg",
    ["CSS 已生成", "复制成功", "本地保存"],
    ["复制", "随机", "角度"],
    0.45,
  ),
  habit: fixture(
    "habit",
    "习惯养成",
    "#22c55e",
    "0 / 8",
    "每天 8 杯水",
    "今日未完成",
    ["连续 0 天", "重置规则：每日", "点击记录"],
    ["打卡", "目标", "历史"],
    0,
  ),
  timestamp: fixture(
    "timestamp",
    "时间戳转换",
    "#475569",
    "1716229200",
    "2026-05-20 23:40",
    "UTC+8",
    ["毫秒/秒切换", "复制结果", "本地计算"],
    ["转换", "复制", "时区"],
    0.54,
  ),
  pomodoro: fixture(
    "pomodoro",
    "番茄时钟",
    "#dc2626",
    "00:00",
    "专注 25 分钟",
    "今日 0 轮",
    ["短休息 5 分钟", "暂停状态", "本地计时"],
    ["开始", "暂停", "设置"],
    0,
  ),
  ipLookup: fixture(
    "ipLookup",
    "IP查询",
    "#0f766e",
    "IP 查询",
    "公网 203.0.113.8",
    "手动刷新",
    ["深圳 · 联通", "延迟 24ms", "历史查询"],
    ["刷新", "复制", "搜索"],
    0.45,
  ),
  worldClock: fixture(
    "worldClock",
    "世界时钟",
    "#0e7490",
    "23:40 北京",
    "08:40 洛杉矶",
    "11:40 纽约",
    ["17:40 伦敦", "UTC+8", "城市列表"],
    ["城市", "排序", "时区"],
    0.82,
  ),
  avatarGenerator: fixture(
    "avatarGenerator",
    "头像生成器",
    "#9333ea",
    "头像",
    "文字/颜色生成",
    "本地导出",
    ["模板 6 个", "无需上传", "PNG 导出"],
    ["生成", "导出", "模板"],
    0.58,
  ),
  relativeCalculator: fixture(
    "relativeCalculator",
    "亲戚计算器",
    "#be123c",
    "亲戚计算",
    "爸爸的姐姐",
    "结果：姑妈",
    ["支持反向称呼", "输入拆分", "本地计算"],
    ["计算", "清空", "反向"],
    0.42,
  ),
  converterSuite: fixture(
    "converterSuite",
    "换算器",
    "#2563eb",
    "换算器",
    "计算器 · 房贷 · 个税",
    "长度单位",
    ["面积单位", "汇率换算", "常用工具"],
    ["单位", "金融", "计算"],
    0.5,
  ),
  numberUppercase: fixture(
    "numberUppercase",
    "数字大写转换",
    "#334155",
    "壹佰贰拾叁",
    "123.00",
    "人民币大写",
    ["支持小数", "复制结果", "格式切换"],
    ["转换", "复制", "清空"],
    0.36,
  ),
};

export const resolveItabFixture = (kind: ItabDataKind) =>
  ITAB_WIDGET_FIXTURES[kind] || ITAB_WIDGET_FIXTURES.memo;
