export {
  assertWidgetShell,
  assertWidgetShellSource,
  findForbiddenWidgetShellSelectors,
  findForbiddenWidgetShellStyleProperties,
  formatWidgetShellViolations,
  ITAB_WIDGET_SHELL_FORBIDDEN_SELECTORS as WIDGET_SHELL_FORBIDDEN_SELECTORS,
  WIDGET_SHELL_FORBIDDEN_STYLE_PROPERTIES,
  ITAB_WIDGET_SHELL_PROFILE,
  ITAB_WIDGET_SHELL_SELECTORS as WIDGET_SHELL_SELECTORS,
  ITAB_WIDGET_SHELL_CONTRACT_VERSION as WIDGET_SHELL_CONTRACT_VERSION,
  validateWidgetShell,
  validateWidgetShellSource,
  WidgetShellContractError,
  type WidgetShellElementName,
  type WidgetShellProfile,
  type WidgetShellRequiredElement,
  type WidgetShellSourceValidationOptions,
  type WidgetShellValidationOptions,
  type WidgetShellValidationResult,
  type WidgetShellViolation,
  type WidgetShellViolationCode,
} from "../widget-shell/WidgetShellContract";
